apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: prova-9-sample-spring-boot-app-k8s-init
  labels:
    backstage.io/kubernetes-id: prova-9-sample-spring-boot-app-k8s
spec:
  params:
    - name: git-revision
      value: master
  pipelineRef:
    name: prova-9-sample-spring-boot-app-k8s
  serviceAccountName: pipeline
  workspaces:
    - name: source-dir
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: sonar-settings
      secret:
        secretName: sonarqube-secret-token
    - configMap:
        name: maven-settings
      name: maven-settings
